// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_7R2rfqnIE0PCJ7LXZ0ZT8KL7VYhgbjs',
    appId: '1:1089712234175:web:8c266a1af7db185f6c300a',
    messagingSenderId: '1089712234175',
    projectId: 'id-generator-bf84a',
    authDomain: 'id-generator-bf84a.firebaseapp.com',
    databaseURL: 'https://id-generator-bf84a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'id-generator-bf84a.appspot.com',
    measurementId: 'G-7VB087NQQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPZP8XaSKzFhPdgoyQLjLfm21GTbnhOZ4',
    appId: '1:1089712234175:android:9c148126af0d40ee6c300a',
    messagingSenderId: '1089712234175',
    projectId: 'id-generator-bf84a',
    databaseURL: 'https://id-generator-bf84a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'id-generator-bf84a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXeOqq6SoHIfAiBURTb9WjvKoTlUpZnGE',
    appId: '1:1089712234175:ios:f69b7bc9fd0620bd6c300a',
    messagingSenderId: '1089712234175',
    projectId: 'id-generator-bf84a',
    databaseURL: 'https://id-generator-bf84a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'id-generator-bf84a.appspot.com',
    iosBundleId: 'com.example.idGenerator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXeOqq6SoHIfAiBURTb9WjvKoTlUpZnGE',
    appId: '1:1089712234175:ios:55ce2bdf921cd6e26c300a',
    messagingSenderId: '1089712234175',
    projectId: 'id-generator-bf84a',
    databaseURL: 'https://id-generator-bf84a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'id-generator-bf84a.appspot.com',
    iosBundleId: 'com.example.idGenerator.RunnerTests',
  );
}
